In [1]:
import numpy as np

In [4]:
#SCALAR QUANTITY
a=np.array(10)
print(a)

10


In [5]:
print("Add",a+5)

Add 15


In [6]:
#VECTOR (1-D ARRAY)

vec=np.array([1,2,3,4,5,6])
print(vec)

[1 2 3 4 5 6]


In [7]:
vec*3

array([ 3,  6,  9, 12, 15, 18])

In [8]:
print(vec+ 15)

[16 17 18 19 20 21]


In [9]:
print(vec +vec)

[ 2  4  6  8 10 12]


In [10]:
print(vec -vec)

[0 0 0 0 0 0]


In [11]:
# MATRIX (2-D ARRAY) Rows & columns
mat=np.array([[1,2,3],[4,5,6]])

print(mat)

[[1 2 3]
 [4 5 6]]


In [12]:
mat +1

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
mat*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
print(mat+3)

[[4 5 6]
 [7 8 9]]


In [16]:
Mat1=np.array([[1,2],[3,4]])

Mat2=np.array([[5,6],[7,8]])

In [17]:
Mat1 + Mat2

array([[ 6,  8],
       [10, 12]])

In [18]:
Mat1 * Mat2

array([[ 5, 12],
       [21, 32]])

In [19]:
Mat1.shape        ### for knowing the shape of matrix

(2, 2)

In [21]:
# Transpose a matrix
Mat1.T

array([[1, 3],
       [2, 4]])

In [23]:
# Determinant
A=np.array([[1,2],[3,4]])

In [24]:
A

array([[1, 2],
       [3, 4]])

In [27]:
det=np.linalg.det(A)
print(det)

# det=ad-bc

-2.0000000000000004


In [28]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
det=np.linalg.det(B)
print(det)

0.0


In [31]:
#det=a(ei-fh)-b(di-fg)+c(dh-eg)

In [32]:
# identity matrix

Iden=np.eye(3)
print(Iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# Diagonal matrix

Diag=np.diag([1,5,7])
print(Diag)

[[1 0 0]
 [0 5 0]
 [0 0 7]]


A=np.array

In [36]:
#linear equation
A=np.array([[1,2],
            [3,4]])

B=np.array([5,6])

In [37]:
# solve linear equation

x=np.linalg.solve(A,B)
print(x)

[-4.   4.5]


In [42]:
A=np.array([[4,5,3],
            [4,1,6],
            [9,8,9]
           ])

B=np.array([6,8,6])

In [43]:
# Solve linear equation
x=np.linalg.solve(A,B)
print(x)

[-80.          36.          48.66666667]
